title: Automation
icon: mdi:flash-auto
cards:
  - type: vertical-stack
    cards:
      - type: custom:button-card
        name: "Automations"
        styles:
          card:
            - background-color: "#203040"

      - type: custom:vertical-stack-in-card
        cards:
          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
            filter:
              include:
                - domain: automation
                  sort: entity_id

  - type: vertical-stack
    cards:
      - type: custom:button-card
        name: "Scripts"
        styles:
          card:
            - background-color: "#203040"
      - type: custom:vertical-stack-in-card
        cards:
          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
            filter:
              include:
                - domain: script
                  sort: entity_id

      - type: custom:button-card
        name: "Settings"
        styles:
          card:
            - background-color: "#203040"
      - type: custom:vertical-stack-in-card
        cards:
          - type: entities
            show_header_toggle: false
            entities:
              - input_boolean.auto_turn_off_lights
              - input_boolean.auto_fan
              - input_boolean.vacuum_schedule
              - input_boolean.pump_schedule
              - input_boolean.boiler_schedule
