title: Automation
#icon: mdi:flash-auto
icon: mdi:home-automation
cards:
  - type: vertical-stack
    cards:
      - type: "custom:button-card"
        name: "Automations"
        styles:
          card:
            - background-color: "#203040"

      - type: custom:vertical-stack-in-card
        cards:
          - type: custom:monster-card
            show_empty: false
            card:
              type: entities
            filter:
              include:
                - entity_id: "automation.*"

  - type: vertical-stack
    cards:
      - type: "custom:button-card"
        name: "Scripts"
        styles:
          card:
            - background-color: "#203040"
      - type: custom:vertical-stack-in-card
        cards:
          - type: custom:monster-card
            show_empty: false
            card:
              type: entities
            filter:
              include:
                - entity_id: "script.*"

      - type: "custom:button-card"
        name: "Settings"
        styles:
          card:
            - background-color: "#203040"
      - type: custom:vertical-stack-in-card
        cards:
          - type: entities
            show_header_toggle: false
            entities:
              - input_boolean.auto_turn_off_lights
              - input_boolean.auto_fan
              - input_boolean.vacuum_schedule

