resources:
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/monster-card/monster-card.js
    type: js
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
    type: js
  - url: /community_plugin/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
    type: module
  - url: /community_plugin/lovelace-valetudo-map-card/valetudo-map-card.js
    type: js

title: Home
views:
  - !include includes/lovelace/home.yaml
# - !include includes/lovelace/climate.yaml
  - !include includes/lovelace/media.yaml
  - !include includes/lovelace/livingroom.yaml
  - !include includes/lovelace/kitchen.yaml
  - !include includes/lovelace/master_bedroom.yaml
  - !include includes/lovelace/bedroom.yaml
  - !include includes/lovelace/hallway.yaml
  - !include includes/lovelace/balcony.yaml
  - !include includes/lovelace/vacuum.yaml
  - !include includes/lovelace/ring.yaml
  - !include includes/lovelace/flowers.yaml
  - !include includes/lovelace/heating.yaml
  - !include includes/lovelace/rf_bridge.yaml
  - !include includes/lovelace/battery.yaml
  - !include includes/lovelace/system.yaml
  - !include includes/lovelace/automation.yaml

