resources:
# - url: /local/custom-lovelace/monster-card/monster-card.js
#   type: js
# - url: /local/tracker-card.js?track=true
#   type: module
# - url: /local/custom-lovelace/group-card/group-card.js
#   type: js
# - url: /local/vertical-stack-in-card.js
#   type: js
# - url: /local/banner-card.js?track=true
#   type: module
# - url: /local/mini-media-player-bundle.js
#   type: module
# - url: /local/mini-graph-card-bundle.js
#   type: module
  - url: /community_plugin/group-card/group-card.js
    type: js
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module

title: Home
views:
  - !include includes/lovelace/home.yaml
  - !include includes/lovelace/media.yaml
  - !include includes/lovelace/livingroom.yaml
  - !include includes/lovelace/kitchen.yaml
  - !include includes/lovelace/master_bedroom.yaml
  - !include includes/lovelace/bedroom.yaml
  - !include includes/lovelace/hallway.yaml
  - !include includes/lovelace/balcony.yaml
  - !include includes/lovelace/battery.yaml
  - !include includes/lovelace/system.yaml
  - !include includes/lovelace/ring.yaml
  - !include includes/lovelace/flowers.yaml
  - !include includes/lovelace/vacuum.yaml
  - !include includes/lovelace/automation.yaml

