- alias: Switch balcony 1
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_158d000183dd12
      click_type: single
  action:
    service: switch.toggle
    entity_id:
      - switch.wall_switch_ln_158d00022ab4bf
      - switch.wall_switch_ln_158d0001f9aa37
      - switch.wall_switch_ln_158d0002114338

- alias: Switch balcony 2
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_158d000183d2d5
      click_type: single
  action:
    service: switch.toggle
    entity_id:
      - switch.wall_switch_ln_158d00022ab4bf
      - switch.wall_switch_ln_158d0001f9aa37
      - switch.wall_switch_ln_158d0002114338

- alias: Turn on christmas lights
  initial_state: 'off'
  trigger:
    platform: time
    at: '18:00:00'
  action:
    service: switch.turn_on
    entity_id: switch.plug_158d0002677c89

- alias: Turn off christmas lights
  initial_state: 'off'
  trigger:
    platform: time
    at: '00:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.plug_158d0002677c89

