- alias: Door opened in Bathroom
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0002fd4381
    to: 'on'
  condition:
    condition: state
    entity_id: switch.wall_switch_ln_left_158d00022a8150
    state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.wall_switch_ln_left_158d00022a8150

- alias: Turn off Bathroom lights 20 minutes after turn on
  initial_state: 'on'
  trigger:
    platform: time_pattern
    minutes: '/1'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.auto_turn_off_lights
        state: 'on'
      - condition: state
        entity_id: switch.wall_switch_ln_left_158d00022a8150
        state: 'on'
        for:
          minutes: 20
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_ln_left_158d00022a8150

- alias: Turn off auto Bathroom fan 5 minutes after turn on
  initial_state: 'on'
  trigger:
    platform: time_pattern
    minutes: '/1'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.sonoff_br_relay_1
        state: 'on'
        for:
          minutes: 5
      - condition: state
        entity_id: input_boolean.br_manaul_fun_on
        state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.sonoff_br_relay_1

- alias: Turn off manual Bathroom fan 15 minutes after turn on
  initial_state: 'on'
  trigger:
    platform: time_pattern
    minutes: '/1'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.sonoff_br_relay_1
        state: 'on'
        for:
          minutes: 15
      - condition: state
        entity_id: input_boolean.br_manaul_fun_on
        state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.sonoff_br_relay_1
    - service: input_boolean.turn_off
      entity_id: input_boolean.br_manaul_fun_on

- alias: Turn on Bathroom fan
  initial_state: 'on'
  trigger:
    - platform: time
      at: '07:45'
    - platform: time
      at: '13:00'
    - platform: time
      at: '18:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.auto_fan
        state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.sonoff_br_relay_1

- alias: Bathroom fan button is pressed to on
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.sonoff_br_button_1
    to: 'on'
  condition:
    condition: state
    entity_id: switch.sonoff_br_relay_1
    state: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.br_manaul_fun_on

- alias: Bathroom fan button is pressed to off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.sonoff_br_button_1
    to: 'off'
  condition:
    condition: state
    entity_id: switch.sonoff_br_relay_1
    state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.br_manaul_fun_on

