- alias: Respond to single button click bedroom2
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.0x00158d0002113ace_click
    to: 'single'
  action:
    - service: light.toggle
      entity_id: light.bedroom_lamp

- alias: Respond to double button click bedroom2
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.0x00158d0002113ace_click
    to: 'double'
  action:
    - service: light.toggle
      entity_id: light.bedroom_lamp

- alias: Set brightness for lamp in bedroom2
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: light.bedroom_lamp
    from: 'off'
    to: 'on'
  action:
    - service: yeelight.set_mode
      data:
        entity_id: light.bedroom_lamp
        mode: normal
