- alias: Set brightness for lamp in bedroom2
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: light.bedroom_lamp
    from: 'off'
    to: 'on'
  action:
    - service: yeelight.set_mode
      data:
        entity_id: light.bedroom_lamp
        mode: normal
