- alias: khadas_ha_server_off
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.ha1_uptime_dt
      to: "unavailable"
      for: "00:02:00"
  action:
    - service: notify.telegram
      data:
        message: 'Не работает ХА на Khadas'

- alias: khadas_ha_server_on
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.ha1_uptime_dt
      from: "unavailable"
  action:
    - service: notify.telegram
      data:
        message: 'Заработал ХА на Khadas'

- alias: raspberry_ha_server_off
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.ha2_uptime_dt
      to: "unavailable"
      for: "00:02:00"
  action:
    - service: notify.telegram
      data:
        message: 'Не работает ХА на Raspberry PI 4'

- alias: raspberry_ha_server_on
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.ha2_uptime_dt
      from: "unavailable"
  action:
    - service: notify.telegram
      data:
        message: 'Заработал ХА на Raspberry PI 4'

