- alias: ha1_server_off
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.ha1_uptime
      to: "unavailable"
      for: "00:02:00"
  action:
    - service: notify.telegram
      data_template:
        message: '{{ states.sensor.date_time.state }} | Не работает HA1'

- alias: ha1_server_on
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.ha1_uptime
      from: "unavailable"
  action:
    - service: notify.telegram
      data_template:
        message: '{{ states.sensor.date_time.state }} | Заработал HA1'

- alias: ha2_server_off
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.ha2_uptime
      to: "unavailable"
      for: "00:02:00"
  action:
    - service: notify.telegram
      data_template:
        message: '{{ states.sensor.date_time.state }} | Не работает HA2'

- alias: ha2_server_on
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.ha2_uptime
      from: "unavailable"
  action:
    - service: notify.telegram
      data_template:
        message: '{{ states.sensor.date_time.state }} | Заработал HA2'

