- alias: HACS Persistent Notification
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.hacs
    above: 0
  condition:
    - condition: template
      value_template: "{{ not is_state('sensor.hacs', 'none') }}"
    - condition: template
      value_template: "{{ not is_state('sensor.hacs', 'unknown') }}"
  action:
    - service: persistent_notification.create
      data:
        message: "Update available!"
        title: "HACS"
