- alias: "Switch hallway 1 on"
  initial_state: 'on'
  trigger:
    platform: state
    from: 'off'
    to: 'on'
    entity_id: switch.wall_switch_ln_158d0002112b1e
  action:
    service: switch.turn_on
    entity_id: switch.wall_switch_ln_158d0001f9aaae

- alias: "Switch hallway 1 off"
  initial_state: 'on'
  trigger:
    platform: state
    from: 'on'
    to: 'off'
    entity_id: switch.wall_switch_ln_158d0002112b1e
  action:
    service: switch.turn_off
    entity_id: switch.wall_switch_ln_158d0001f9aaae

- alias: "Switch hallway 2 on"
  initial_state: 'on'
  trigger:
    platform: state
    from: 'off'
    to: 'on'
    entity_id: switch.wall_switch_ln_158d0001f9aaae
  action:
    service: switch.turn_on
    entity_id: switch.wall_switch_ln_158d0002112b1e

- alias: "Switch hallway 2 off"
  initial_state: 'on'
  trigger:
    platform: state
    from: 'on'
    to: 'off'
    entity_id: switch.wall_switch_ln_158d0001f9aaae
  action:
    service: switch.turn_off
    entity_id: switch.wall_switch_ln_158d0002112b1e

- alias: "Turn on lights in hallway when door is opened"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00032b7db7
    to: 'on'
  condition:
    condition: state
    entity_id: switch.wall_switch_ln_158d0002112b1e
    state: 'off'
    for:
      minutes: 2
  action:
    - service: notify.telegram
      data:
        message: "Открылась дверь в квартиру"
    - service: switch.turn_on
      entity_id:
        - switch.wall_switch_ln_158d0002112b1e
        - switch.wall_switch_ln_158d0001f9aaae

- alias: "Turn off light in hallway after 6 minutes"
  initial_state: 'on'
  trigger:
    platform: time_pattern
    minutes: '/1'
  condition:
    - condition: state
      entity_id: input_boolean.auto_turn_off_lights
      state: 'on'
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d00032b7db7
      state: 'off'
    - condition: state
      entity_id: switch.wall_switch_ln_158d0002112b1e
      state: 'on'
      for:
        minutes: 6
  action:
    service: switch.turn_off
    entity_id:
      - switch.wall_switch_ln_158d0002112b1e
      - switch.wall_switch_ln_158d0001f9aaae

- alias: "Turn off switch-3 in hallway after 5 minutes"
  initial_state: 'on'
  trigger:
    platform: time_pattern
    minutes: '/1'
  condition:
    - condition: state
      entity_id: input_boolean.auto_turn_off_lights
      state: 'on'
    - condition: state
      entity_id: switch.wall_switch_ln_right_158d00022a8150
      state: 'on'
      for:
        minutes: 5
  action:
    service: switch.turn_off
    entity_id: switch.wall_switch_ln_right_158d00022a8150

- alias: "Hallway Button Click Hold"
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002e22617
      click_type: hold
  action:
    - service: input_boolean.toggle
      entity_id: input_boolean.auto_turn_off_lights

