#- alias: Turn on lights in kitchen if movement
#  initial_state: 'off'
#  trigger:
#    - platform: state
#      entity_id: binary_sensor.motion_sensor_158d00022515fe
#      to: 'on'
#  condition:
#    condition: and
#    conditions:
#      - condition: template
#        value_template: "{{ states.sun.sun.attributes.elevation | int < 12 }}"
#      - condition: state
#        entity_id: switch.wall_switch_ln_158d000211434a
#        state: 'off'
#  action:
#    - service: switch.turn_on
#      entity_id:
#        - switch.wall_switch_ln_158d000211434a

- alias: Turn on lights in kitchen if movement 2
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00022515fe
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.illumination_158d00022515fe
        below: 10
      - condition: state
        entity_id: switch.wall_switch_ln_158d000211434a
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id:
        - switch.wall_switch_ln_158d000211434a

- alias: Turn off lights in kitchen after last movement 15 min ago
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00022515fe
    to: 'off'
    for:
      minutes: 15
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.auto_turn_off_lights
        state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_ln_158d000211434a
    - service: light.turn_off
      entity_id: light.kitchen_lamp

- alias: Set brightness for lamp in kitchen
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: light.kitchen_lamp
    from: 'off'
    to: 'on'
  action:
    - service: yeelight.set_mode
      data:
        entity_id: light.kitchen_lamp
        mode: normal
