# Kitchen
- alias: "Turn on light in kitchen on conditions"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00022515fe
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.illumination_158d00022515fe
      below: 10
    - condition: state
      entity_id: switch.wall_switch_ln_158d000211434a
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.wall_switch_ln_158d000211434a

- alias: "Reset kitchen timer on conditions"
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d00022515fe
  condition:
    - condition: state
      entity_id: switch.wall_switch_ln_158d000211434a
      state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.kitchen
    - service: timer.start
      entity_id: timer.kitchen

- alias: "Turn off light in kitchen on conditions"
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.kitchen
  condition:
    - condition: state
      entity_id: input_boolean.auto_turn_off_lights
      state: 'on'
    - condition: state
      entity_id: switch.wall_switch_ln_158d000211434a
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_ln_158d000211434a
    - service: light.turn_off
      entity_id: light.kitchen_lamp

- alias: "Turn on kitchen timer if light is on"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.wall_switch_ln_158d000211434a
      to: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.kitchen
    - service: timer.start
      entity_id: timer.kitchen

- alias: "Turn off kitchen timer if light is off"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.wall_switch_ln_158d000211434a
      to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.kitchen

- alias: "Turn on timer if kitchen light is on"
  initial_state: 'on'
  trigger:
    - platform: time_pattern
      minutes: '/1'
  condition:
    - condition: state
      entity_id: switch.wall_switch_ln_158d000211434a
      state: 'on'
    - condition: state
      entity_id: timer.kitchen
      state: 'idle'
  action:
    - service: timer.cancel
      entity_id: timer.kitchen
    - service: timer.start
      entity_id: timer.kitchen

- alias: "Set brightness for lamp in kitchen"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: light.kitchen_lamp
    from: 'off'
    to: 'on'
  action:
    service: yeelight.set_mode
    data:
      entity_id: light.kitchen_lamp
      mode: normal
