- alias: Respond to single button click
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.0x00158d000211434a_click
    to: 'single'
  action:
    - service: light.toggle
      entity_id: light.living_room_lamp

- alias: Respond to double button click
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.0x00158d000211434a_click
    to: 'double'
  action:
    - service: light.toggle
      entity_id: light.living_room_lamp

- alias: Respond to left button click
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.0x00158d00022b3ea0_click
    to: 'left_single'
  action:
    - service: light.toggle
      entity_id: group.living_room_spot_left

- alias: Respond to right button click
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.0x00158d00022b3ea0_click
    to: 'right_single'
  action:
    - service: light.toggle
      entity_id: group.living_room_spot_right

- alias: Respond to both buttons click
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.0x00158d00022b3ea0_click
    to: 'both_single'
  action:
    - service: light.toggle
      entity_id:
        - group.living_room_spot_right
        - group.living_room_spot_left

- alias: Set brightness for lamp in living-room
  initial_state: true
  trigger:
    platform: state
    entity_id: light.living_room_lamp
    to: 'on'
  action:
    - service: yeelight.set_mode
      data:
        entity_id: light.living_room_lamp
        mode: normal

