- alias: Respond to left button click
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.0x00158d00022b3ea0_click
    to: 'left_single'
  action:
    - service: light.toggle
      entity_id: group.living_room_spot_left

- alias: Respond to right button click
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.0x00158d00022b3ea0_click
    to: 'right_single'
  action:
    - service: light.toggle
      entity_id: group.living_room_spot_right

- alias: Respond to both buttons click
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.0x00158d00022b3ea0_click
    to: 'both_single'
  action:
    - service: light.toggle
      entity_id:
        - group.living_room_spot_right
        - group.living_room_spot_left

