#- alias: Respond to single button click
#  initial_state: 'on'
#  trigger:
#    platform: state
#    entity_id: sensor.0x00158d000211434a_click
#    to: 'single'
#  action:
#    - service: light.toggle
#      entity_id: light.living_room_lamp

#- alias: Respond to single button click main switch 1
#  initial_state: 'on'
#  trigger:
#    platform: state
#    entity_id: sensor.0x00158d000211434a_click
#    to: 'single'
#  condition:
#      condition: state
#      entity_id: light.living_room_lamp
#      state: 'off'
#  action:
#    - service: light.turn_on
#      data_template:
#        entity_id: light.living_room_lamp
#        brightness_pct: >
#          {% if now().hour > 0 and now().hour < 6 %}
#            1
#          {% else %}
#            80
#          {% endif %}
#
#- alias: Respond to single button click main switch 2
#  initial_state: 'on'
#  trigger:
#    platform: state
#    entity_id: sensor.0x00158d000211434a_click
#    to: 'single'
#  condition:
#      condition: state
#      entity_id: light.living_room_lamp
#      state: 'on'
#  action:
#    - service: light.turn_off
#      entity_id: light.living_room_lamp

#- alias: Respond to double button click main switch
#  initial_state: 'on'
#  trigger:
#    platform: state
#    entity_id: sensor.0x00158d000211434a_click
#    to: 'double'
#  action:
#    - service: light.toggle
#      entity_id: light.living_room_lamp

- alias: Respond to left button click
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.0x00158d00022b3ea0_click
    to: 'left_single'
  action:
    - service: light.toggle
      entity_id: group.living_room_spot_left

- alias: Respond to right button click
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.0x00158d00022b3ea0_click
    to: 'right_single'
  action:
    - service: light.toggle
      entity_id: group.living_room_spot_right

- alias: Respond to both buttons click
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.0x00158d00022b3ea0_click
    to: 'both_single'
  action:
    - service: light.toggle
      entity_id:
        - group.living_room_spot_right
        - group.living_room_spot_left

#- alias: Set brightness for lamp in living-room
#  initial_state: 'on'
#  trigger:
#    platform: state
#    entity_id: light.living_room_lamp
#    from: 'off'
#    to: 'on'
#  action:
#    - service: yeelight.set_mode
#      data:
#        entity_id: light.living_room_lamp
#        mode: normal

