- alias: "Set brightness for lamp in bedroom1"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: light.master_bedroom_lamp
    from: 'off'
    to: 'on'
  action:
    - service: yeelight.set_mode
      data:
        entity_id: light.master_bedroom_lamp
        mode: normal

- alias: "Turn on bedside lamp"
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: 7
    above: 5
  condition:
    - condition: state
      state: 'off'
      entity_id: light.bedside
    - condition: time
      after: '15:00:00'
      before: '22:00:00'
  action:
    service: light.turn_on
    entity_id: light.bedside
    data_template:
      brightness_pct: 70
      kelvin: 6500

- alias: "Turn off bedside lamp"
  initial_state: 'on'
  trigger:
    platform: time
    at: '02:00:00'
  condition:
    condition: state
    entity_id: light.bedside
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.bedside

