- alias: Respond to single button click bedroom1
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.0x00158d0001f9aa24_click
    to: 'single'
  action:
    - service: light.toggle
      entity_id: light.master_bedroom_lamp

- alias: Respond to double button click bedroom1
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.0x00158d0001f9aa24_click
    to: 'double'
  action:
    - service: light.toggle
      entity_id: light.master_bedroom_lamp

- alias: Set brightness for lamp in bedroom1
  initial_state: true
  trigger:
    platform: state
    entity_id: light.master_bedroom_lamp
    to: 'on'
  action:
    - service: yeelight.set_mode
      data:
        entity_id: light.master_bedroom_lamp
        mode: normal

- alias: Turn on bedside lamp
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: 7
    above: 5
  condition:
    condition: state
    state: 'off'
    entity_id: light.bedside
  action:
    service: light.turn_on
    entity_id: light.bedside

- alias: Turn off bedside lamp
  initial_state: 'on'
  trigger:
    platform: time
    at: '02:00:00'
  condition:
    condition: state
    entity_id: light.bedside
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.bedside

