- alias: 'Time Pump Off'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '09:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.pump_schedule
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun
  action:
    - service: switch.turn_off
      entity_id: switch.sonoff_pump_relay

- alias: 'Time Pump On'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '17:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.pump_schedule
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun
  action:
    - service: switch.turn_on
      entity_id: switch.sonoff_pump_relay

