- alias: "Power state sonoff on HA start-up"
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "sonoffs/cmnd/state"
        payload: ""

- alias: "Enable MQTT discovery for all sonoff devices"
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffs/SetOption19"
        payload: "1"

- alias: Sonoff Firmware Installed
  initial_state: 'on'
  trigger:
  - event: start
    platform: homeassistant
  action:
  - service: mqtt.publish
    data:
      payload: '2'
      topic: sonoffs/cmnd/status
