# Notify if electricity is off
- alias: notify_electricity_off
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
          # коридор
        - switch.wall_switch_ln_158d0001f9aaae
          # спальня 1
        - switch.0x00158d0001f9aa24_switch
          # спальня 2
        - switch.0x00158d0002113ace_switch
          # зал
#       - switch.0x00158d000211434a_switch
          # балкон
        - switch.wall_switch_ln_158d00022ab4bf
          # кухня
        - switch.0x00158d00022addd4_switch_left
      to: 'unavailable'
      for:
        seconds: 60
  action:
    - service: notify.telegram
      data:
        message: "Возможно пропало электричество"
    - service: automation.turn_off
      entity_id: automation.notify_electricity_off

# Notify if electricity is on
- alias: notify_electricity_on
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
          # коридор
        - switch.wall_switch_ln_158d0001f9aaae
          # спальня 1
        - switch.0x00158d0001f9aa24_switch
          # спальня 2
        - switch.0x00158d0002113ace_switch
          # зал
#       - switch.0x00158d000211434a_switch
          # балкон
        - switch.wall_switch_ln_158d00022ab4bf
          # кухня
        - switch.0x00158d00022addd4_switch_left
      from: 'unavailable'
#     for:
#       seconds: 60
  action:
    - service: notify.telegram
      data:
        message: "Появилось электричество"
    - service: automation.turn_on
      entity_id: automation.notify_electricity_off

