# WC
- alias: "Turn on light in WC on conditions"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00024de627
      to: 'on'
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0004466f8f
  condition:
    - condition: state
      entity_id: switch.wall_switch_ln_158d00022360fe
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.wall_switch_ln_158d00022360fe
    - service: timer.cancel
      entity_id: timer.kitchen
    - service: timer.start
      entity_id: timer.wc

- alias: "Reset WC timer on conditions"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00024de627
      to: 'off'
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0004466f8f
  condition:
    - condition: state
      entity_id: switch.wall_switch_ln_158d00022360fe
      state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.kitchen
    - service: timer.start
      entity_id: timer.wc

- alias: "Turn off light in WC on conditions"
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.wc
  condition:
    - condition: state
      entity_id: input_boolean.auto_turn_off_lights
      state: 'on'
    - condition: state
      entity_id: switch.wall_switch_ln_158d00022360fe
      state: 'on'
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d00024de627
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_ln_158d00022360fe

- alias: "Turn off wc timer if light is off"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.wall_switch_ln_158d00022360fe
      to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.wc

- alias: "Turn on timer if wc light is on"
  initial_state: 'on'
  trigger:
    - platform: time_pattern
      minutes: '/1'
  condition:
    - condition: state
      entity_id: switch.wall_switch_ln_158d00022360fe
      state: 'on'
    - condition: state
      entity_id: timer.wc
      state: 'idle'
  action:
    - service: timer.cancel
      entity_id: timer.wc
    - service: timer.start
      entity_id: timer.wc


# FAN

- alias: "Turn off auto WC fan 5 minutes after turn on"
  initial_state: 'on'
  trigger:
    platform: time_pattern
    minutes: '/1'
  condition:
    - condition: state
      entity_id: switch.sonoff_wc_relay
      state: 'on'
      for:
        minutes: 5
    - condition: state
      entity_id: input_boolean.wc_manaul_fun_on
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.sonoff_wc_relay

- alias: "Turn off manual WC fan 15 minutes after turn on"
  initial_state: 'on'
  trigger:
    platform: time_pattern
    minutes: '/1'
  condition:
    - condition: state
      entity_id: switch.sonoff_wc_relay
      state: 'on'
      for:
        minutes: 15
    - condition: state
      entity_id: input_boolean.wc_manaul_fun_on
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.sonoff_wc_relay
    - service: input_boolean.turn_off
      entity_id: input_boolean.wc_manaul_fun_on

- alias: "Turn on WC fan"
  initial_state: 'on'
  trigger:
    - platform: time
      at: '07:45'
    - platform: time
      at: '13:00'
    - platform: time
      at: '18:00'
  condition:
    - condition: state
      entity_id: input_boolean.auto_fan
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.sonoff_wc_relay

- alias: "WC fan button is pressed to on"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.sonoff_wc_button
    to: 'on'
  condition:
    condition: state
    entity_id: switch.sonoff_wc_relay
    state: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.wc_manaul_fun_on

- alias: "WC fan button is pressed to off"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.sonoff_wc_button
    to: 'off'
  condition:
    condition: state
    entity_id: switch.sonoff_wc_relay
    state: 'off'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.wc_manaul_fun_on

