automation:
  - alias: 'Notify when UPS goes on battery'
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.mustek_status
        from: 'ONLINE'
        to: 'ONBATT'
    action:
      - service: notify.telegram
        data:
          message: "Пропало напряжение в сети. Время: {{ states('sensor.time_date') }}"

  - alias: 'Notify when UPS goes on ac'
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.mustek_status
        from: 'ONBATT'
        to: 'ONLINE'
    action:
      - service: notify.telegram
        data:
          message: "Восстановлено напряжение в сети. Время: {{ states('sensor.time_date') }}"
