automation:
  - alias: Plant Data Update
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.miflore1_moisture, sensor.miflore2_moisture, sensor.miflore3_moisture
        below: 30
    action:
      - service: notify.telegram
        data_template:
          message: "Этому цветку необходима вода - '{{ trigger.from_state.attributes.friendly_name }}', влажность {{ trigger.from_state.state }} "
