group:
  flowers:
    view: yes
    icon: mdi:flower
    name: Цветы
    control: hidden
    entities:
      - group.flower1
      - group.flower2
      - group.flower3

  flower1:
    name: Цветок 1
    control: hidden
    entities:
      - sensor.miflore1_temperature
      - sensor.miflore1_light
      - sensor.miflore1_moisture
      - sensor.miflore1_conductivity
      - sensor.miflore1_battery

  flower2:
    name: Цветок 2
    control: hidden
    entities:
      - sensor.miflore2_temperature
      - sensor.miflore2_light
      - sensor.miflore2_moisture
      - sensor.miflore2_conductivity
      - sensor.miflore2_battery

  flower3:
    name: Цветок 3
    control: hidden
    entities:
      - sensor.miflore3_temperature
      - sensor.miflore3_light
      - sensor.miflore3_moisture
      - sensor.miflore3_conductivity
      - sensor.miflore3_battery

automation:
  - alias: Plant Data Update
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.miflore1_moisture, sensor.miflore2_moisture, sensor.miflore3_moisture
        below: 30
    action:
      - service: notify.telegram
        data_template:
          message: "Этому цветку необходима вода - '{{ trigger.from_state.attributes.friendly_name }}', влажность {{ trigger.from_state.state }} "
