ring:
  username: !secret ring_user
  password: !secret ring_pass

ffmpeg:

binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion

sensor:
  - platform: ring
    monitored_conditions:
      - battery
      - last_activity
      - last_ding
      - last_motion
      - volume

  - platform: template
    sensors:
      front_door_last_activity_date:
        friendly_name: Последняя активность
        icon_template: mdi:clock
        value_template: "{{ as_timestamp(state_attr('sensor.front_door_last_activity', 'created_at')) | timestamp_custom('%H:%M %d-%m-%Y') }}"

      front_door_last_ding_date:
        friendly_name: Последний звонок
        icon_template: mdi:clock
        value_template: "{{ as_timestamp(state_attr('sensor.front_door_last_ding', 'created_at')) | timestamp_custom('%H:%M %d-%m-%Y') }}"

      front_door_last_motion_date:
        friendly_name: Последние движение
        icon_template: mdi:clock
        value_template: "{{ as_timestamp(state_attr('sensor.front_door_last_motion', 'created_at')) | timestamp_custom('%H:%M %d-%m-%Y') }}"

camera:
  - platform: ring

downloader:
  download_dir: downloads

automation:
  - alias: Ring DoorBell
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: binary_sensor.front_door_ding
      to: 'on'
    action:
      - service: notify.telegram
        data:
          message: 'Звонок в дверь'

  - alias: Ring Video Download
    initial_state: 'on'
    trigger:
      platform: template
      value_template: "{{ is_state_attr('sensor.front_door_last_activity', 'recording_status', 'ready') }}"
    action:
      - service: downloader.download_file
        data_template:
          subdir: "ring_{{ now().strftime('%Y_%m_%d') }}"
          filename: "motion_{{ now().strftime('%Y_%m_%d_%H_%M') }}.mpg"
          overwrite: true
          url: "{{ state_attr('camera.front_door', 'video_url') }}"

