substitutions:
  device_name: nodemcu_1

esphome:
  name: ${device_name}
  platform: ESP32
  board: nodemcu-32s
  #arduino_version: 1.0.2
  platformio_options:
    upload_speed: 115200

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  fast_connect: true
  ap:
    ssid: ${device_name}
    password: !secret wifi_pass_2

logger:
# level: VERBOSE

api:
ota:
web_server:

esp32_ble_tracker:
  scan_parameters:
    interval: 320ms
    window: 30ms

#dallas:
#  - pin: GPIO23

binary_sensor:
  - platform: status
    name: ${device_name}_status

sensor:
  - platform: xiaomi_lywsdcgq
    mac_address: !secret kitchen_bt_mac
    temperature:
      name: kitchen_bt_temperature
    humidity:
      name: kitchen_bt_humidity
    battery_level:
      name: kitchen_bt_battery_level

  - platform: xiaomi_lywsdcgq
    mac_address: !secret living_room_bt_mac
    temperature:
      name: living_room_bt_temperature
    humidity:
      name: living_room_bt_humidity
    battery_level:
      name: living_room_bt_battery_level

  - platform: uptime
    name: ${device_name}_uptime

  - platform: wifi_signal
    name: ${device_name}_wifi_signal

text_sensor:
  - platform: version
    name: ${device_name}_esphome_version
    icon: mdi:chip

  - platform: wifi_info
    ip_address:
      name: ${device_name}_ip_address
    ssid:
      name: ${device_name}_connected_ssid

switch:
  - platform: restart
    name: ${device_name}_restart

