substitutions:
  device_name: nodemcu_1

esphome:
  name: ${device_name}
  platform: ESP32
  board: nodemcu-32s

wifi:
  output_power: 20dB
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  use_address: 192.168.1.33

captive_portal:
logger:
api:
ota:

esp32_ble_tracker:
  scan_parameters:
    interval: 320ms
    window: 30ms

binary_sensor:
  - platform: status
    name: ${device_name}_status

sensor:
  - platform: xiaomi_lywsdcgq
    mac_address: !secret kitchen_bt_mac
    temperature:
      name: kitchen_bt_temperature
    humidity:
      name: kitchen_bt_humidity
    battery_level:
      name: kitchen_bt_battery_level

  - platform: xiaomi_lywsdcgq
    mac_address: !secret living_room_bt_mac
    temperature:
      name: living_room_bt_temperature
    humidity:
      name: living_room_bt_humidity
    battery_level:
      name: living_room_bt_battery_level

  - platform: uptime
    name: ${device_name}_uptime
    icon: mdi:timer-outline

  - platform: wifi_signal
    name: ${device_name}_wifi_signal
    icon: mdi:wifi

# - platform: template
#   name: ${device_name}_free_heap
#   icon: mdi:memory
#   lambda: "return ESP.getFreeHeap();"
#   update_interval: 20s
#   unit_of_measurement: bytes
#   accuracy_decimals: 0

text_sensor:
  - platform: version
    name: ${device_name}_esphome_version
    icon: mdi:information-outline

  - platform: wifi_info
    ip_address:
      name: ${device_name}_ip_address
      icon: mdi:ip-network
    ssid:
      name: ${device_name}_connected_ssid
      icon: mdi:access-point

switch:
  - platform: restart
    name: ${device_name}_restart
    icon: mdi:restart
