substitutions:
  device_name: nodemcu_3

esphome:
  name: ${device_name}
  platform: ESP32
  board: nodemcu-32s

wifi:
  output_power: 20dB
  fast_connect: true
  ssid: !secret wifi_ssid_3
  password: !secret wifi_pass_3

logger:
api:
ota:
captive_portal:

esp32_ble_tracker:
  scan_parameters:
#   interval: 320ms
#   window: 30ms
    interval: 512ms
    window: 48ms

dallas:
  - pin: GPIO13

binary_sensor:
  - platform: status
    name: ${device_name}_status

sensor:
  - platform: uptime
    name: ${device_name}_uptime
    icon: mdi:timer

  - platform: wifi_signal
    name: ${device_name}_wifi_signal
    icon: mdi:wifi

  - platform: template
    name: ${device_name}_free_heap
    icon: mdi:memory
    lambda: "return ESP.getFreeHeap();"
    update_interval: 20s
    unit_of_measurement: bytes
    accuracy_decimals: 0

  - platform: xiaomi_hhccjcy01
    mac_address: !secret miflora1
    temperature:
      name: mf1_temperature
    moisture:
      name: mf1_moisture
    illuminance:
      name: mf1_illuminance
    conductivity:
      name: mf1_soil

  - platform: xiaomi_hhccjcy01
    mac_address: !secret miflora2
    temperature:
      name: mf2_temperature
    moisture:
      name: mf2_moisture
    illuminance:
      name: mf2_illuminance
    conductivity:
      name: mf2_soil

  - platform: xiaomi_hhccjcy01
    mac_address: !secret miflora3
    temperature:
      name: mf3_temperature
    moisture:
      name: mf3_moisture
    illuminance:
      name: mf3_illuminance
    conductivity:
      name: mf3_soil

  - platform: dallas
    address: !secret dallas_2
    name: ${device_name}_outdoor_temperature

text_sensor:
  - platform: version
    name: ${device_name}_esphome_version
    icon: mdi:information-outline

  - platform: wifi_info
    ip_address:
      name: ${device_name}_ip_address
      icon: mdi:ip-network
    ssid:
      name: ${device_name}_connected_ssid
      icon: mdi:access-point

switch:
  - platform: restart
    name: ${device_name}_restart
    icon: mdi:restart
