substitutions:
  device_name: nodemcu_2

esphome:
  name: ${device_name}
  platform: ESP8266
  board: nodemcuv2
  #arduino_version: 2.4.2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  ap:
    ssid: ${device_name}
    password: !secret wifi_pass_2

logger:
api:
ota:
#web_server:

binary_sensor:
  - platform: status
    name: ${device_name}_status

sensor:
  - platform: uptime
    name: ${device_name}_uptime

  - platform: wifi_signal
    name: ${device_name}_wifi_signal

text_sensor:
  - platform: version
    name: ${device_name}_esphome_version
    icon: mdi:chip

  - platform: wifi_info
    ip_address:
      name: ${device_name}_ip_address
    ssid:
      name: ${device_name}_connected_ssid

switch:
  - platform: restart
    name: ${device_name}_restart

