# Sonoff T1
substitutions:
  device_name: sonoff_wc

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  output_power: 20dB
  ssid: !secret wifi_ssid_3
  password: !secret wifi_pass_3
  manual_ip:
    static_ip: 192.168.1.106
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 1.1.1.1

logger:
api:
ota:
captive_portal:

switch:
  - platform: gpio
    pin: GPIO12
    id: relay

  - platform: template
    name: ${device_name}_relay
    optimistic: true
    id: relayandled
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: led
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: led

  - platform: restart
    name: ${device_name}_restart

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
      inverted: true
    name: ${device_name}_button
    on_press:
      - switch.toggle: relay

  - platform: status
    name: ${device_name}_status

sensor:
  - platform: uptime
    name: ${device_name}_uptime
    icon: mdi:timer-outline

  - platform: wifi_signal
    name: ${device_name}_wifi_signal
    icon: mdi:wifi

# - platform: template
#   name: ${device_name}_free_heap
#   icon: mdi:memory
#   lambda: "return ESP.getFreeHeap();"
#   update_interval: 20s
#   unit_of_measurement: bytes
#   accuracy_decimals: 0

text_sensor:
  - platform: version
    name: ${device_name}_esphome_version
    icon: mdi:information-outline

  - platform: wifi_info
    ip_address:
      name: ${device_name}_ip_address
      icon: mdi:ip-network
    ssid:
      name: ${device_name}_connected_ssid
      icon: mdi:access-point

output:
  - platform: esp8266_pwm
    id: sonoff_blue_led
    pin:
      number: GPIO13
      inverted: true

light:
  - platform: monochromatic
    name: ${device_name}_blue_led
    output: sonoff_blue_led
    id: led

