substitutions:
  device_name: sonoff_basic_2

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_pass
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_pass_2
  ap:
    ssid: ${device_name}
    password: !secret wifi_pass

logger:

api:

ota:

web_server:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
      inverted: true
    name: ${device_name}_button
    on_press:
      - switch.toggle: fakebutton

  - platform: status
    name: ${device_name}_status

switch:
  - platform: template
    name: ${device_name}_relay
    optimistic: true
    id: fakebutton
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: led
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: led

  - platform: gpio
    id: relay
    pin: GPIO12

  - platform: restart
    name: ${device_name}_restart

output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin:
      number: GPIO13
      inverted: true

light:
  - platform: monochromatic
    name: ${device_name}_green_led
    output: basic_green_led
    id: led

sensor:
  - platform: uptime
    name: ${device_name}_uptime

  - platform: wifi_signal
    name: ${device_name}_wifi_signal

text_sensor:
  - platform: version
    name: ${device_name}_esphome_version
    icon: mdi:chip

  - platform: wifi_info
    ip_address:
      name: ${device_name}_ip_address
      icon: mdi:target
    ssid:
      name: ${device_name}_connected_ssid

