substitutions:
  device_name: sonoff_plug_1
  current_res: '0.00221'
  voltage_div: '871'

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  ap:
    ssid: ${device_name}
    password: !secret wifi_pass

logger:

api:

ota:

web_server:

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    name: ${device_name}_button
    pin:
      number: GPIO03
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay

  - platform: status
    name: ${device_name} status

switch:
  - platform: gpio
    id: relay
    name: ${device_name}_relay
    icon: mdi:power-socket-eu
    restore_mode: ALWAYS_ON
    pin: GPIO14
    on_turn_on:
      - switch.turn_on: blue_led
    on_turn_off:
      - switch.turn_off: blue_led

  - platform: gpio
    id: blue_led
    name: ${device_name}_led_blue
    icon: mdi:led-on
    restore_mode: ALWAYS_ON
    pin:
      number: GPIO01
      inverted: true

  - platform: gpio
    id: red_led
    name: ${device_name}_led_red
    icon: mdi:led-on
    restore_mode: ALWAYS_OFF
    pin:
      number: GPIO13
      inverted: true

  - platform: restart
    name: ${device_name}_restart

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: ${device_name}_current
      icon: mdi:current-ac
      unit_of_measurement: A
    voltage:
      name: ${device_name}_voltage
      icon: mdi:flash-circle
      unit_of_measurement: V
    power:
      name: ${device_name}_power
      icon: mdi:flash-outline
      unit_of_measurement: W
      id: ${device_name}_power
    change_mode_every: 8
    update_interval: 10s

  - platform: total_daily_energy
    name: ${device_name}_daily_energy
    icon: mdi:circle-slice-3
    power_id: ${device_name}_power
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh

  - platform: uptime
    name: ${device_name}_uptime

  - platform: wifi_signal
    name: ${device_name}_wifi_signal

text_sensor:
  - platform: version
    name: ${device_name}_esphome_version
    icon: mdi:chip

  - platform: wifi_info
    ip_address:
      name: ${device_name}_ip_address
    ssid:
      name: ${device_name}_connected_ssid

