substitutions:
  device_name: sonoff_rf_br_1
  repeat_wait: '10ms'
  repeat_times: '5'

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  output_power: 20dB
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_pass
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_pass_2
  ap:
    ssid: ${device_name}
    password: !secret wifi_pass_2

logger:
api:
ota:
captive_portal:
#web_server:

binary_sensor:
  - platform: status
    name: ${device_name}_status

  - platform: remote_receiver
    name: ${device_name}_sb_rf
    device_class: power
    rc_switch_raw:
      code: '000010110000100110010100'
      protocol: 1
    filters:
      delayed_off: 5s

  - platform: remote_receiver
    name: ${device_name}_gate1
    device_class: door
    rc_switch_raw:
      code: '000000110101111100000100'
      protocol: 1
    filters:
      delayed_off: 5s

  - platform: remote_receiver
    name: ${device_name}_gate2
    device_class: door
    rc_switch_raw:
      code: '111001111110000000001000'
      protocol: 1
    filters:
      delayed_off: 5s

  - platform: remote_receiver
    name: ${device_name}_key4
    device_class: power
    rc_switch_raw:
      code: '001011100001101000011'
      protocol: 1
    filters:
      delayed_off: 5s

sensor:
  - platform: wifi_signal
    name: ${device_name}_wifi_signal

  - platform: uptime
    name: ${device_name}_uptime

text_sensor:
  - platform: version
    name: ${device_name}_esphome_version
    icon: mdi:chip

  - platform: wifi_info
    ip_address:
      name: ${device_name}_ip_address
    ssid:
      name: ${device_name}_connected_ssid

switch:
  - platform: restart
    name: ${device_name}_restart

  - platform: template
    name: ${device_name}_sb_rf
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '000010110000100110010100'
          protocol: 1
          repeat:
            wait_time: ${repeat_wait}
            times: ${repeat_times}

  - platform: template
    name: ${device_name}_gate1
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '000000110101111100000100'
          protocol: 1
          repeat:
            wait_time: ${repeat_wait}
            times: ${repeat_times}

  - platform: template
    name: ${device_name}_gate2
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '111001111110000000001000'
          protocol: 1
          repeat:
            wait_time: ${repeat_wait}
            times: ${repeat_times}

  - platform: template
    name: ${device_name}_key4
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '001011100001101000011000'
          protocol: 1
          repeat:
            wait_time: ${repeat_wait}
            times: ${repeat_times}

remote_receiver:
  pin: 4
  dump: rc_switch
  tolerance: 50
  filter: 4us
  idle: 4ms

remote_transmitter:
  pin: 5
  carrier_duty_percent: 100%

status_led:
  pin:
    number: GPIO13
    inverted: yes


