substitutions:
  device_name: sonoff_rf_1

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  output_power: 20dB
# fast_connect: true
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_pass
      priority: 20
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_pass_2
      priority: 10
  ap:
    ssid: ${device_name}
    password: !secret wifi_pass_2
    ap_timeout: 3min

logger:
api:
ota:
captive_portal:
#web_server:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
      inverted: true
    name: ${device_name}_button
    on_press:
      - switch.toggle: fakebutton

  - platform: status
    name: ${device_name}_status

sensor:
  - platform: wifi_signal
    name: ${device_name}_wifi_signal

  - platform: uptime
    name: ${device_name}_uptime

  - platform: template
    name: ${device_name}_free_heap
    lambda: "return ESP.getFreeHeap();"
    update_interval: 20s
    unit_of_measurement: bytes
    accuracy_decimals: 0

text_sensor:
  - platform: version
    name: ${device_name}_esphome_version
    icon: mdi:chip

  - platform: wifi_info
    ip_address:
      name: ${device_name}_ip_address
    ssid:
      name: ${device_name}_connected_ssid

switch:
  - platform: template
    name: ${device_name}_relay
    optimistic: true
    id: fakebutton
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: led
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: led

  - platform: gpio
    id: relay
    pin: GPIO12
    #restore_mode: always_on
    restore_mode: always_off

  - platform: restart
    name: ${device_name}_restart

output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin:
      number: GPIO13
      inverted: true

light:
  - platform: monochromatic
    name: ${device_name}_green_led
    output: basic_green_led
    id: led
