substitutions:
  device_name: sonoff_wc

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  #arduino_version: dev
  #arduino_version: 2.4.2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  ap:
    ssid: ${device_name}
    password: !secret wifi_pass

logger:

api:

ota:

web_server:

output:
  - platform: esp8266_pwm
    id: sonoff_blue_led
    pin:
      number: GPIO13
      inverted: true

light:
  - platform: monochromatic
    name: ${device_name}_blue_led
    output: sonoff_blue_led
    id: led

switch:
  - platform: gpio
    pin: GPIO12
    id: relay

  - platform: template
    name: ${device_name}_relay
    optimistic: true
    id: relayandled
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: led
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: led

  - platform: restart
    name: ${device_name}_restart"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
      inverted: true
    name: ${device_name}_button
    on_press:
      - switch.toggle: relay

  - platform: status
    name: ${device_name}_status

sensor:
  - platform: uptime
    name: ${device_name}_uptime

  - platform: wifi_signal
    name: ${device_name}_wifi_signal

text_sensor:
  - platform: version
    name: ${device_name}_esphome_version

  - platform: wifi_info
    ip_address:
      name: ${device_name}_ip_address
    ssid:
      name: ${device_name}_connected_ssid
