substitutions:
  device_name: sonoff_pow2

#sonoff pow r2
esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_pass
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_pass_2
  ap:
    ssid: ${device_name}
    password: !secret wifi_pass

logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

api:

ota:

web_server:

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
      inverted: true
    name: ${device_name}_button
    on_press:
      - switch.toggle: fakebutton

  - platform: status
    name: ${device_name}_status

switch:
  - platform: template
    name: ${device_name}_relay
    optimistic: true
    id: fakebutton
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: led
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: led

  - platform: gpio
    id: relay
    pin: GPIO12

  - platform: restart
    name: ${device_name}_restart

output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO13
      inverted: true

light:
  - platform: monochromatic
    name: ${device_name}_blue_led
    output: pow_blue_led
    id: led

sensor:
  - platform: cse7766
    current:
      name: ${device_name}_current
      icon: mdi:current-ac
      unit_of_measurement: A
    voltage:
      name: ${device_name}_voltage
      icon: mdi:flash-circle
      unit_of_measurement: V
    power:
      name: ${device_name}_power
      icon: mdi:flash-outline
      unit_of_measurement: W
      id: ${device_name}_power
      on_value_range:
        - above: 4.0
          then:
            - light.turn_on: led
        - below: 3.0
          then:
            - light.turn_off: led
    update_interval: 10s

  - platform: total_daily_energy
    name: ${device_name}_daily_energy
    icon: mdi:circle-slice-3
    power_id: ${device_name}_power
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh

  - platform: wifi_signal
    name: ${device_name}_wifi_signal

  - platform: uptime
    name: ${device_name}_uptime

text_sensor:
  - platform: version
    name: ${device_name}_esphome_version
    icon: mdi:chip

  - platform: wifi_info
    ip_address:
      name: ${device_name}_ip_address
    ssid:
      name: ${device_name}_connected_ssid
