substitutions:
  device_name: sonoff_br

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  output_power: 20dB
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
# ap:
#   ssid: ${device_name}
#   password: !secret wifi_pass

logger:
api:
ota:
#web_server:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
      inverted: true
    name: ${device_name}_button_1
    on_press:
      - switch.toggle: relay_1

  - platform: gpio
    pin:
      number: GPIO09
      mode: INPUT_PULLUP
      inverted: true
    name: ${device_name}_button_2
    on_press:
      - switch.toggle: relay_2

  - platform: status
    name: ${device_name}_status

sensor:
  - platform: uptime
    name: ${device_name}_uptime

  - platform: wifi_signal
    name: ${device_name}_wifi_signal

text_sensor:
  - platform: version
    name: ${device_name}_esphome_version
    icon: mdi:chip

  - platform: wifi_info
    ip_address:
      name: ${device_name}_ip_address
    ssid:
      name: ${device_name}_connected_ssid

switch:
  - platform: gpio
    name: ${device_name}_relay_1
    pin: GPIO12
    id: relay_1

  - platform: gpio
    name: ${device_name}_relay_2
    pin: GPIO5
    id: relay_2

  - platform: restart
    name: ${device_name}_restart

output:
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: true

light:
  - platform: monochromatic
    name: ${device_name}_blue_led
    output: blue_led
    internal: true
    id: blue_led_light

